FORMAT: 1A
HOST: http://lukaapi.apiblueprint.org/

# Luka API

Luka documentation.

NOTE: This document is **work in Progress**.
TODOs: add error status reply

## Introduction

basic description. Link to readme file.

## Testing

Testing guidelines.

# Group Person

## Person Collection [/person]

A Person that signs contracts and payments with billers.

+ Attributes  (Person)

### Create a Person [POST /biller]

Create a Person.

+ Request
  + Attributes  (Person)

+ Response 201 (application/json)
  + Attributes  (Person)

### Get a Person [GET /person/{id}]

Get a specific Person based on his handle (phone number).

+ Parameter
  + id: 38553745530 - Person id (phone number).

+ Response 200 (application/json)
  + Attributes  (Person)

### Get all People [GET /person]

Get all people in the system.

+   Parameter
    + countryCode:  HR (optional, string)
      + default:  BO

+   Response 200  (application/json)
    + Attributes  (array[Person])

## Payment Collection [/payment]

A Payment that completes a contract between Person and Biller.

+ Attributes  (Payment)

### Create a Payment  [POST /payment]

Initiate a Payment between Biller and Person.

### Update a Payment status [PUT /payment]

Update the status of the payment.

### Get a Payment [GET /payment/{handle}]

Get a Payment status.

#Group Biller

Test.

## Biller Collection  [/biller]

A provider of service that completes the pledge with a person.

+ Attributes  (Biller)

### Create a Biller [POST /biller]

Create a Biller.

### Get all Billers [GET /biller]

Get all Billers.

### Get a Biller  [GET /biller/{id}]

Get a Biller based on his handle.

### Get Biller Contract  [GET /biller/{id}/contract]

A Pledge is an agreement between People and Billers.
Get Pledges that are related to a Biller.

## Contract Collection  [/contract]

A Contract between a Person and a Biller.

+ Attributes  (Contract)

### Create a contract [POST /contract]

Creates a Contract.

# Data Structures

##  Location  (object)
- street: nikola tesla house (string) - Street
- city: Smiljan (string) - City
- zip: 53211 (string) - Zip code
- country: Croatia (string) - Country
- countryCode: HRV (string) - Country code ISO

##  Labels  (object)
- labels (object) - Free input object
    - firstLabel: firstText (string)

##  Person  (object)
- id: 1234123423 (string, required) - Id
- firstName: Nikola (string, required) - First name
- lastName: Tesla (string, required) - Last name
- phone: 38553745530 (string, optional) - Phone number
- email: nikola@tesla.com (string) - Email address
- facebook: 1234231423423 (string) - Facebook url
- created: 2016-08-17T18:58:47.630Z - Date created
- Include Locations
- Include Labels


##  Biller  (object)
- id: 'fdsafdsfa' (string) - Biller id
- handle: yambal-bo (string, required) - Handle
- legalName: Yambal Bolivias (string) - Legal name
- website: https://www.yambal.bo (string) - website
- Include Location
- Include Labels

##  Products  (object)
- id: 23434123 (string) - Product id
- source: yambal-bo (string, required)  - Biller Id
- signer: hash1234234 (string, required)  - Core has signer
- Include Labels

## Contract (object)
- id: 'fdsafdsfa' (string) - Biller id
- target: product-id (string, required) - Person Id
- Include Labels

## Payment (object)
- id: d1efdsafds (string) - Payment Id
- source: person-id (string) - Person Id
- target: product-id (string) - Product Id
- amount: 1000 (number) - Amount of payment
- symbol: BOB (string)  - Currency symbol
- Include Labels
